version: '3.8'

services:
  mtg-csv-processor:
    build: .
    container_name: mtg-csv-processor
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./public:/app
      - ./mtg.db:/app/mtg.db:ro
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    networks:
      - mtg-network

