name: Create CMDR CSV

on:
  schedule:
    # Run monthly on Sunday at 3am UTC
    - cron: '0 3 * * 0'
  workflow_dispatch:
    # Allow manual trigger

jobs:
  create-cmdr-csv:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests ijson bz2file
          
      - name: Download data and create database
        run: |
          python build_db.py --download True
          python build_db.py --db mtg.db --scry default-cards.json --skus TcgplayerSkus.json.bz2

      - name: Create zip of CMDR CSVs
        run: | 
          python decklist_cmdr/build_cmdr_csv.py
          zip -r decklist_cmdr/tcgplayer_cmdr_csv.zip decklist_cmdr/tcgplayer_cmdr_csv/*.csv
      
      # Get date for release tag
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
          
      # Create GitHub Release with the zip file
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: cmdr-csv-${{ steps.date.outputs.date }}
          name: CMDR CSV ${{ steps.date.outputs.date }}
          files: decklist_cmdr/tcgplayer_cmdr_csv.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN}}

      # Post to Discord with the public download link
      - name: Post to Discord
        uses: appleboy/discord-action@v1.2.0
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: |
            New CSV files available for download: https://github.com/${{ github.repository }}/releases/download/cmdr-csv-${{ steps.date.outputs.date }}/tcgplayer_cmdr_csv.zip