name: Update MTG Database

on:
  schedule:
    # Run weekly on Sunday at 3am UTC
    - cron: '0 3 * * 0'
  workflow_dispatch:
    # Allow manual trigger

jobs:
  update-mtg-db:
    runs-on: self-hosted
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests ijson bz2file
          
      - name: Download data and create database
        run: |
          python build_db.py --download True
          python build_db.py --db mtg.db --scry default-cards.json --skus TcgplayerSkus.json.bz2
          
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'placeholder'
          config: |
            Host server
              HostName ${{ secrets.SSH_HOST }}
              User ${{ secrets.SSH_USER }}
              IdentityFile ~/.ssh/id_rsa
              StrictHostKeyChecking no
          
      - name: Deploy to production server
        run: |
          # Transfer the new database directly to the destination folder
          scp mtg.db server:${{ secrets.DATABASE_LOCATION }}/mtg.db.new
          
          # Stop the container, replace the database, and start it again
          ssh server "cd ${{ secrets.DOCKER_COMMAND_LOCATION }} && \
            docker compose down mtg-csv && \
            cd ${{ secrets.DATABASE_LOCATION }} && \
            mv mtg.db.new mtg.db && \
            cd ${{ secrets.DOCKER_COMMAND_LOCATION }} && \
            docker compose up -d  mtg-csv"
            
          echo "Database successfully updated and service restarted"
